name: dogs_app
description: "dogs_app"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #STATE MANAGEMENT
  flutter_bloc: ^8.1.5
  #NETWORK
  http: ^1.2.0
  #UTILITIES
  equatable: ^2.0.5
  get_it: ^7.6.7
  #Cached_network_image
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
